name: Reusable Deploy
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deployable artifact file
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output content
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
  