name: Reusable Deploy
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: Output content
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
  